import type { MetadataRoute } from 'next'

import { SITE } from '@/content/site'

/**
 * Required under `output: 'export'`. Metadata routes compile to route handlers,
 * and static export refuses to collect one that has not declared itself static.
 * This is the same mechanism that makes opengraph-image.tsx unreliable under
 * static export: that convention has no way to opt in, which is why the social
 * card is generated by a script and committed instead.
 */
export const dynamic = 'force-static'

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: SITE.name,
    short_name: SITE.shortName,
    description: SITE.description,
    start_url: '/',
    display: 'standalone',
    // Light-mode surface. The theme-colour meta in the layout handles the
    // per-scheme values; this is the install-time splash colour.
    background_color: '#ede0d4',
    theme_color: '#ede0d4',
    icons: [{ src: '/icon.svg', sizes: 'any', type: 'image/svg+xml' }],
  }
}
