import type { MetadataRoute } from 'next'

import { SITE } from '@/content/site'

/**
 * Required under `output: 'export'`. Metadata routes compile to route handlers,
 * and static export refuses to collect one that has not declared itself static.
 * This is the same mechanism that makes opengraph-image.tsx unreliable under
 * static export: that convention has no way to opt in, which is why the social
 * card is generated by a script and committed instead.
 */
export const dynamic = 'force-static'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [{ userAgent: '*', allow: '/' }],
    sitemap: new URL('/sitemap.xml', SITE.url).toString(),
  }
}
