import type { MetadataRoute } from 'next'

import { SITE } from '@/content/site'
import { STATIONS } from '@/content/stations'

/**
 * Required under `output: 'export'`. Metadata routes compile to route handlers,
 * and static export refuses to collect one that has not declared itself static.
 * This is the same mechanism that makes opengraph-image.tsx unreliable under
 * static export: that convention has no way to opt in, which is why the social
 * card is generated by a script and committed instead.
 */
export const dynamic = 'force-static'

/** Emits out/sitemap.xml at build. Derived from STATIONS so it cannot drift. */
export default function sitemap(): MetadataRoute.Sitemap {
  return STATIONS.map((station) => ({
    url: new URL(station.href, SITE.url).toString(),
    changeFrequency: 'monthly',
    priority: station.href === '/' ? 1 : 0.7,
  }))
}
